// frontend/admin/src/components/GenealogyTree/index.tsx
import { ReactElement, useEffect, useRef, useMemo } from 'react';
import * as d3 from 'd3';
import type { GenealogyTreeProps, TreeNode, NodeRenderConfig } from './types';
import { personToTreeNode, buildTree } from './utils';
import styles from './index.module.css';

const DEFAULT_CONFIG: NodeRenderConfig = {
  width: 120,
  height: 60,
  horizontalSpacing: 30,
  verticalSpacing: 80,
  nodeColor: {
    male: '#e6f7ff',
    female: '#fff1f0',
    selected: '#1890ff',
    alive: '#52c41a',
    deceased: '#8c8c8c',
  },
};

export function GenealogyTree({
  data,
  selectedNodeId,
  onNodeClick,
  config,
}: GenealogyTreeProps): ReactElement {
  const svgRef = useRef<SVGSVGElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const mergedConfig = useMemo(() => ({ ...DEFAULT_CONFIG, ...config }), [config]);

  // 转换数据为树结构
  const treeData = useMemo(() => {
    if (!data) return null;
    const centerNode = personToTreeNode(data.centerPerson);
    const ancestors = data.ancestors.map(personToTreeNode);
    const descendants = data.descendants.map(personToTreeNode);
    return buildTree({ centerPerson: centerNode, ancestors, descendants });
  }, [data]);

  useEffect(() => {
    if (!svgRef.current || !containerRef.current || !treeData) return;

    const svg = d3.select(svgRef.current);
    svg.selectAll('*').remove();

    const container = containerRef.current;
    const { width, height } = container.getBoundingClientRect();

    // 创建缩放组
    const g = svg.append('g')
      .attr('class', 'zoom-group')
      .attr('transform', `translate(${width / 2}, 60)`);

    // 创建树布局
    const hierarchy = d3.hierarchy<TreeNode>(treeData.rootNode, (d) => d.children);
    const treeLayout = d3.tree<TreeNode>()
      .nodeSize([mergedConfig.width + mergedConfig.horizontalSpacing, mergedConfig.height + mergedConfig.verticalSpacing]);

    const treeRoot = treeLayout(hierarchy);

    // 绘制连接线
    const linksGroup = g.append('g').attr('class', 'links');
    linksGroup.selectAll('path')
      .data(treeRoot.links())
      .enter()
      .append('path')
      .attr('class', styles.link)
      .attr('d', (d) => {
        const sourceX = d.source.x;
        const sourceY = d.source.y + mergedConfig.height / 2;
        const targetX = d.target.x;
        const targetY = d.target.y - mergedConfig.height / 2;
        const midY = (sourceY + targetY) / 2;
        return `M ${sourceX} ${sourceY} C ${sourceX} ${midY}, ${targetX} ${midY}, ${targetX} ${targetY}`;
      })
      .attr('fill', 'none')
      .attr('stroke', '#d9d9d9')
      .attr('stroke-width', 1.5);

    // 绘制节点
    const nodesGroup = g.append('g').attr('class', 'nodes');
    const nodes = nodesGroup.selectAll('g')
      .data(treeRoot.descendants())
      .enter()
      .append('g')
      .attr('class', styles.node)
      .attr('transform', (d) => `translate(${d.x - mergedConfig.width / 2}, ${d.y - mergedConfig.height / 2})`)
      .style('cursor', 'pointer')
      .on('click', (_, d) => {
        onNodeClick?.(d.data);
      });

    // 节点背景
    nodes.append('rect')
      .attr('width', mergedConfig.width)
      .attr('height', mergedConfig.height)
      .attr('rx', 4)
      .attr('fill', (d) => {
        const isSelected = d.data.id === selectedNodeId;
        if (isSelected) return mergedConfig.nodeColor.selected;
        return d.data.gender === '男' ? mergedConfig.nodeColor.male : mergedConfig.nodeColor.female;
      })
      .attr('stroke', (d) => {
        const isSelected = d.data.id === selectedNodeId;
        return isSelected ? mergedConfig.nodeColor.selected : '#d9d9d9';
      })
      .attr('stroke-width', (d) => (d.data.id === selectedNodeId ? 2 : 1));

    // 姓名文字
    nodes.append('text')
      .attr('x', mergedConfig.width / 2)
      .attr('y', mergedConfig.height / 2 - 6)
      .attr('text-anchor', 'middle')
      .attr('dominant-baseline', 'middle')
      .attr('font-size', 14)
      .attr('font-weight', 500)
      .attr('fill', '#262626')
      .text((d) => d.data.name);

    // 字号文字
    nodes.append('text')
      .attr('x', mergedConfig.width / 2)
      .attr('y', mergedConfig.height / 2 + 10)
      .attr('text-anchor', 'middle')
      .attr('dominant-baseline', 'middle')
      .attr('font-size', 11)
      .attr('fill', '#8c8c8c')
      .text((d) => d.data.styleName || '');

    // 性别图标
    nodes.append('text')
      .attr('x', 8)
      .attr('y', 12)
      .attr('font-size', 12)
      .attr('fill', '#8c8c8c')
      .text((d) => (d.data.gender === '男' ? '♂' : '♀'));

    // 存活状态图标
    nodes.append('circle')
      .attr('cx', mergedConfig.width - 12)
      .attr('cy', 12)
      .attr('r', 5)
      .attr('fill', (d) => (d.data.isAlive ? mergedConfig.nodeColor.alive : mergedConfig.nodeColor.deceased));

    // 设置缩放
    const zoom = d3.zoom<SVGSVGElement, unknown>()
      .scaleExtent([0.3, 3])
      .on('zoom', (event) => {
        g.attr('transform', event.transform);
      });

    svg.call(zoom);

    // 初始居中
    const initialTransform = d3.zoomIdentity.translate(width / 2, 80).scale(0.8);
    svg.call(zoom.transform, initialTransform);

  }, [treeData, selectedNodeId, onNodeClick, mergedConfig]);

  return (
    <div ref={containerRef} className={styles.container}>
      <svg ref={svgRef} className={styles.svg} />
    </div>
  );
}

// frontend/visualization/src/components/GenealogyTree/index.vue
<template>
  <div class="genealogy-tree" ref="container">
    <svg ref="svgRef"></svg>
    <div class="tree-controls">
      <button @click="zoomIn" title="放大">+</button>
      <button @click="zoomOut" title="缩小">-</button>
      <button @click="resetZoom" title="重置">⟲</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch, nextTick } from 'vue'
import * as d3 from 'd3'
import type { Person } from '@/types'

interface TreeNode {
  id: number
  name: string
  generation: number
  gender: string
  styleName?: string
  birthYear?: number
  deathYear?: number
  children?: TreeNode[]
}

const props = defineProps<{
  data: TreeNode | null
}>()

const emit = defineEmits<{
  (e: 'node-click', person: Person): void
}>()

const container = ref<HTMLElement | null>(null)
const svgRef = ref<SVGSVGElement | null>(null)
const zoom = ref<d3.ZoomBehavior<SVGSVGElement, unknown> | null>(null)

const NODE_WIDTH = 120
const NODE_HEIGHT = 60
const HORIZONTAL_SPACING = 40
const VERTICAL_SPACING = 100

function buildTree(data: TreeNode): d3.HierarchyNode<TreeNode> {
  return d3.hierarchy(data)
}

function renderTree() {
  if (!svgRef.value || !container.value || !props.data) return

  const svg = d3.select(svgRef.value)
  svg.selectAll('*').remove()

  const width = container.value.clientWidth
  const height = container.value.clientHeight

  svg.attr('width', width).attr('height', height)

  const g = svg.append('g')

  const root = buildTree(props.data)
  const treeLayout = d3.tree<TreeNode>()
    .nodeSize([NODE_WIDTH + HORIZONTAL_SPACING, NODE_HEIGHT + VERTICAL_SPACING])

  treeLayout(root)

  g.selectAll('.link')
    .data(root.links())
    .enter()
    .append('path')
    .attr('class', 'link')
    .attr('d', d3.linkVertical<d3.HierarchyLink<TreeNode>, d3.HierarchyPointNode<TreeNode>>()
      .x(d => d.x + NODE_WIDTH / 2)
      .y(d => d.y + NODE_HEIGHT / 2)
    )
    .attr('fill', 'none')
    .attr('stroke', '#DEB887')
    .attr('stroke-width', 2)

  const nodes = g.selectAll('.node')
    .data(root.descendants())
    .enter()
    .append('g')
    .attr('class', 'node')
    .attr('transform', d => `translate(${d.x}, ${d.y})`)
    .style('cursor', 'pointer')
    .on('click', (_event, d) => {
      emit('node-click', {
        member_id: d.data.id,
        name: d.data.name,
        gender: d.data.gender,
        generation: d.data.generation,
        lineage_path: '',
        style_name: d.data.styleName,
        birth_year: d.data.birthYear,
        death_year: d.data.deathYear
      })
    })

  nodes.append('rect')
    .attr('width', NODE_WIDTH)
    .attr('height', NODE_HEIGHT)
    .attr('x', 0)
    .attr('y', 0)
    .attr('rx', 8)
    .attr('fill', d => d.data.gender === 'M' ? '#E8F4FD' : '#FDE8F4')
    .attr('stroke', d => d.data.gender === 'M' ? '#1890FF' : '#EB2F96')
    .attr('stroke-width', 2)

  nodes.append('text')
    .attr('x', NODE_WIDTH / 2)
    .attr('y', NODE_HEIGHT / 2 - 8)
    .attr('text-anchor', 'middle')
    .attr('dominant-baseline', 'middle')
    .attr('font-size', '14px')
    .attr('font-weight', '600')
    .attr('fill', '#333')
    .text(d => d.data.name)

  nodes.append('text')
    .attr('x', NODE_WIDTH / 2)
    .attr('y', NODE_HEIGHT / 2 + 12)
    .attr('text-anchor', 'middle')
    .attr('dominant-baseline', 'middle')
    .attr('font-size', '11px')
    .attr('fill', '#666')
    .text(d => `第${d.data.generation}代`)

  zoom.value = d3.zoom<SVGSVGElement, unknown>()
    .scaleExtent([0.1, 4])
    .on('zoom', (event) => {
      g.attr('transform', event.transform)
    })

  svg.call(zoom.value)

  const initialX = width / 2
  const initialY = 60
  svg.call(zoom.value.transform, d3.zoomIdentity.translate(initialX, initialY))
}

function zoomIn() {
  if (svgRef.value && zoom.value) {
    d3.select(svgRef.value).transition().call(zoom.value.scaleBy, 1.3)
  }
}

function zoomOut() {
  if (svgRef.value && zoom.value) {
    d3.select(svgRef.value).transition().call(zoom.value.scaleBy, 0.7)
  }
}

function resetZoom() {
  if (svgRef.value && zoom.value && container.value) {
    const width = container.value.clientWidth
    d3.select(svgRef.value).transition().call(
      zoom.value.transform,
      d3.zoomIdentity.translate(width / 2, 60)
    )
  }
}

onMounted(() => {
  nextTick(() => {
    renderTree()
  })
})

watch(() => props.data, () => {
  nextTick(() => {
    renderTree()
  })
})
</script>

<style scoped>
.genealogy-tree {
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
}

.genealogy-tree svg {
  width: 100%;
  height: 100%;
}

.tree-controls {
  position: absolute;
  bottom: 20px;
  right: 20px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.tree-controls button {
  width: 40px;
  height: 40px;
  border: none;
  border-radius: 50%;
  background: var(--color-primary);
  color: white;
  font-size: 1.2rem;
  cursor: pointer;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  transition: transform 0.2s;
}

.tree-controls button:hover {
  transform: scale(1.1);
}
</style>
